"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, <FULL NAME> and <FULL NAME>, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1:
UT EID 2:
"""


class Node:
    """
    A modified version of the Node class for linked lists (using proper class
    coding practices). Instead of a data instance variable, this node class has both
    a coefficient and an exponent instance variable, which is used to represent each
    term in a polynomial.
    """

    def __init__(self, coeff, exp, link=None):
        """
        Node Constructor for polynomial linked lists.

        Args:
        - coeff: The coefficient of the term.
        - exp: The exponent of the term.
        - link: The next node in the linked list.
        """
        self.coeff = coeff
        self.exp = exp
        self.next = link

    @property
    def coeff(self):
        """
        Getter method for the coefficient attribute.
        """
        return self.__coeff

    @coeff.setter
    def coeff(self, value):
        """
        Setter method for the coefficient attribute.
        """
        if value is None or isinstance(value, int):
            self.__coeff = value
        else:
            raise ValueError("Coefficient must be an integer or None.")

    @property
    def exp(self):
        """
        Getter method for the exponent attribute.
        """
        return self.__exp

    @exp.setter
    def exp(self, value):
        """
        Setter method for the exponent attribute.
        """
        if value is None or isinstance(value, int):
            self.__exp = value
        else:
            raise ValueError("Exponent must be an integer or None.")

    @property
    def next(self):
        """
        Getter method for the next attribute.
        """
        return self.__next

    @next.setter
    def next(self, value):
        """
        Setter method for the next attribute.
        """
        if value is None or isinstance(value, Node):
            self.__next = value
        else:
            raise ValueError("Next must be a Node instance or None.")

    def __str__(self):
        """
        String representation of each term in a polynomial linked list.
        """
        return f"({self.coeff}, {self.exp})"


class LinkedList:
    def __init__(self):
        # You are also welcome to use a sentinel/dummy node!
        # It is definitely recommended, which will we learn more
        # about in class on Monday 10/21. If you choose to use
        # a dummy node, you can comment out the self.head = None
        # and comment in the below line. We use None to make sure
        # if there is an error where you accidentally include the
        # dummy node in your calculation, it will throw an error.
        # self.dummy = Node(None, None)
        self.head = None

    # Insert the term with the coefficient coeff and exponent exp into the polynomial.
    # If a term with that exponent already exists, add the coefficients together.
    # You must keep the terms in descending order by exponent.
    def insert_term(self, coeff, exp):
        if coeff == 0:
            return
        
        new_node = Node(coeff, exp)
        inserted = False

        if self.head is None or new_node.exp > self.head.exp:
            new_node.next = self.head
            self.head = new_node
            inserted = True
        
        current = self.head

        while current.next is not None and not inserted:
            if current.next.exp > new_node.exp:
                current = current.next
            elif current.next.exp == new_node.exp:
                if current.next.coeff + new_node.coeff == 0:
                    current.next = current.next.next
                else:
                    current.next.coeff += new_node.coeff
                inserted = True
            else:
                new_node.next = current.next
                current.next = new_node
                inserted = True
        
        if not inserted:
            current.next = new_node
                


    # Add a polynomial p to the polynomial and return the resulting polynomial as a new linked list.
    def add(self, p):
        poly_sum = LinkedList()

        current = self.head
        while current is not None:
            poly_sum.insert_term(current.coeff, current.exp)
            current = current.next

        current = p.head
        while current is not None:
            poly_sum.insert_term(current.coeff, current.exp)
            current = current.next
        
        return poly_sum

    # Multiply a polynomial p with the polynomial and return the product as a new linked list.
    def mult(self, p):
        poly_product = LinkedList()

        current_first_poly = self.head

        while current_first_poly is not None:
            current_second_poly = self.head
            while current_second_poly is not None:
                coeff_product = current_first_poly.coeff * current_second_poly.coeff
                exp_sum = current_first_poly.exp + current_second_poly.exp
                poly_product.insert_term(coeff_product, exp_sum)
                current_second_poly = current_second_poly.next
            current_first_poly = current_first_poly.next
        
        return poly_product

    # Return a string representation of the polynomial.
    def __str__(self):
        terms_list = []
        current = self.head

        if current is None:
            return ""

        while current is not None:
            terms_list.append(f"({current.coeff}, {current.exp})")
        
        return "+".join(terms_list)


def main():
    # read data from stdin using input() and create polynomial p

    # read data from stdin using input() and create polynomial q

    # get sum of p and q as a new linked list and print sum

    # get product of p and q as a new linked list and print product
    import sys
    input = sys.stdin.read
    data = input().strip().splitlines()
    
    p = LinkedList()
    n = int(data[0])
    for i in range(1, n + 1):
        coeff_exp = data[i].split()
        coeff = int(coeff_exp[0])
        exp = int(coeff_exp[1])
        p.insert_term(coeff, exp)
    
    q = LinkedList()
    m = int(data[n + 2])
    for j in range(n + 3, n + 3 + m):
        coeff_exp = data[j].split()
        coeff = int(coeff_exp[0])
        exp = int(coeff_exp[1])
        q.insert_term(coeff, exp)
    
    print(p.add(q))
    print(p.mult(q))


if __name__ == "__main__":
    main()
